use_frameworks!

platform :ios, '13.0'

target 'AGT_Example' do
  pod 'AGT', :path => '../'
  pod 'R.swift', '~> 6.1.0'
  pod 'Swifter'
  pod 'SwiftyJSON'
  pod 'SSZipArchive'

  target 'AGT_Tests' do
    inherit! :search_paths
  end

  target 'AGT_UITests' do
    inherit! :search_paths
    pod 'R.swift', '~> 6.1.0'
    pod 'Swifter'
    pod 'SwiftyJSON'
    pod 'SSZipArchive'
  end

  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
          end
      end
  end

end
